	<!-- Modal STATUS -->
	<div id="statusModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
		  <div class="modal-header">
			<h4 class="modal-title">Change status</h4>
			<button type="button" class="close" data-dismiss="modal">&times;</button>
		  </div>
		  <div class="modal-body">

		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-warning modal-btn" data-dismiss="modal">Change</button>
		  </div>
		</div>

	  </div>
	</div>

	<!-- Modal DEL -->
	<div id="deleteModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
		  <div class="modal-header">
			<h4 class="modal-title">Delete</h4>
			<button type="button" class="close" data-dismiss="modal">&times;</button>
		  </div>
		  <div class="modal-body">

		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-danger modal-btn" data-dismiss="modal">Delete</button>
		  </div>
		</div>

	  </div>
	</div>