  <h2>All tasks from user <?= $user['login'] ?></h2>
  <div class="table-responsive">
	<table class="table table-striped">
	  <thead>
		<tr>
		  <th>#</th>
		  <th>Task ID</th>
		  <th>Text</th>
		  <th>Status</th>
		</tr>
	  </thead>
	  <tbody>
	<?php

	$i = 0;
	foreach($tasks as $task):
	$i++;
	?>

		<tr>
		  <td><?= $i ?></td>
		  <td><?= $task['id'] ?></td>
		  <td><?= $task['task'] ?></td>
		  <td><?= $task['status'] == '' ? 'not performed' : 'done' ?></td>
		</tr>
	<?php endforeach; ?>

	  </tbody>
	</table>
  </div>
