<?php foreach($tasks as $task): ?>
<div class="task">
  <div class="task-text <?= $task['status']?>"><?= $task['task']?></div>
  <div class="btns" task_id="<?= $task['id'] ?>" user_id="<?= $task['user_id'] ?>" >
  <div class="btn-group-toggle done" data-toggle="buttons">
    <label class="btn btn-outline-success">
      <input type="checkbox" data-toggle="buttons"><i class="fa fa-check" aria-hidden="true"></i>
    </label>
  </div>
  <a href="#" class="btn btn-outline-warning" role="button" aria-pressed="true">
    <i class="fa fa-pencil" aria-hidden="true"></i>
  </a>
  <a href="#" class="btn btn-outline-danger" role="button" aria-pressed="true">
    <i class="fa fa-trash" aria-hidden="true"></i>
  </a>
  </div>
</div>
<?php endforeach; ?>
